### ISSUE TITLE
（小问题） 不知道我能不能翻译成粤语？

### ISSUE THREAD

**Issue by GuihongWang** [wrzrmzx/Patchyvideo.txt#1]
小小的翻译一下

**Comment by wrzrmzx** [comment]
如果可以的话那真的是非常感谢，不过现在这个文本项目因为当时修改了项目结构这里的文本已经被弃用了（捂脸）
现在新页面的话还没完成所以文本也没整理好orz
不过欢迎进群一起讨论吖（tg，discord，QQ都行w，就在帕琪站页脚有写）
